routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\ArtikelController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\HelperController;
use App\Http\Controllers\IgnoreKataController;
use App\Http\Controllers\KelompokKonsolidasi;
use App\Http\Controllers\KementrianController;
use App\Http\Controllers\KeteranganController;
use App\Http\Controllers\MailController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\PaketKonsolidasiController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SirupController;
use App\Http\Controllers\RepositoryController;
use App\Http\Controllers\UserController;
use App\Models\Banner;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Http;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   
    return view('welcome');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');


Route::get('/populer', function () {
    return view('tabel-populer');
});
Route::get('/kontak', [PageController::class, 'kontak'])->name('kontak');
Route::get('/contoh-konsolidasi', [PageController::class, 'contohKonsolidasi'])->name('contoh-konsolidasi');
Route::get('/test-mail', [MailController::class, 'composeEmail']);
Route::get('/test-mail-curl', [MailController::class, 'curlEmail']);
Route::get('send-mail', function () {
   
    $data = array('name'=>"Virat Gandhi");
   
      Mail::send(['text'=>'mail'], $data, function($message) {
         $message->to('dadittya.adi@gmail.com', 'Dadittya')->subject
            ('Testing Email from LKPP Project');
         $message->from('dadittya.smtp@gmail.com','Dadittya');
      });
      echo "Basic Email Sent. Check your inbox.";
});

Route::get('tahapan-konsolidasi', function () {
    return view('tahapan-konsolidasi');
})->name('tahapan-konsolidasi');

Route::get('test-api', function() {
    set_time_limit(0);
    
    $respons = Http::get('https://inaproc.lkpp.go.id/isb/api/316a729d-0df1-4bb4-90a8-76a8b6d36c3a/json/736986884/PaketPenyediaOpt1618/tipe/4:12/parameter/2021:K38');

    return $respons;
});
//Kementrian Route
Route::get('/', [KementrianController::class, 'index'])->name('kementrian-lembaga');
Route::post('/kementrian-lembaga', [KementrianController::class, 'getKl'])->name('kementrian-get-kl');
Route::post('/pemerintah-daerah', [KementrianController::class, 'getPemda'])->name('kementrian-get-pemda');
Route::post('/satker', [KementrianController::class, 'getSatker'])->name('kementrian-get-satker');
Route::get('/last-paket', [KementrianController::class, 'getLastPaket'])->name('kementrian-get-last-paket');
Route::post('/jenis-pengadaan', [KementrianController::class, 'getJenisPengadaan'])->name('kementrian-get-jenis-pengadaan');
Route::post('/kementrian-lembaga/kata-popular', [KementrianController::class, 'kataPopular'])->name('kementrian-lembaga.kata-popular');
Route::get('/kementrian-lembaga/kata-popular/data', [KementrianController::class, 'datatable'])->name('kementrian-lembaga.kata-popular-data');
Route::get('/kementrian-lembaga/kata-popular/get-jumlah-paket', [KementrianController::class, 'getJumlahPaket'])->name('kementrian-lembaga.get-jumlah-paket');
Route::get('/kementrian-lembaga/kata-popular/get-jumlah-kata', [KementrianController::class, 'getJumlahKata'])->name('kementrian-lembaga.get-jumlah-kata');
Route::post('/kementrian-lembaga/detail-paket', [KementrianController::class, 'detailPaketAsli'])->name('kementrian-lembaga.data-paket-detail');
Route::post('/kementrian-lembaga/ignore-word', [KementrianController::class, 'datatable'])->name('kementrian-lembaga.ignore-word');

//Add & Store Konsolidasi
Route::post('/store-paket-konsolidasi', [PaketKonsolidasiController::class, 'storePaket'])->name('store-paket-konsolidasi');
//Get Data Konsolidasi
Route::get('/paket-konsolidasi', [PaketKonsolidasiController::class, 'getAllData'])->name('get-paket-konsolidasi');
Route::get('/paket-konsolidasi-data', [PaketKonsolidasiController::class, 'konsolidasiDatatable'])->name('get-paket-konsolidasi-data');
Route::post('/paket-konsolidasi-delete', [PaketKonsolidasiController::class, 'konsolidasiDelete'])->name('get-paket-konsolidasi-delete');
Route::post('/paket-konsolidasi-delete-all', [PaketKonsolidasiController::class, 'konsolidasiDeleteAll'])->name('paket-konsolidasi-delete-all');


//Detail Konsolidasi
Route::get('/paket-konsolidasi-detail/{konsolidasi_id}/{klasifikasi?}', [PaketKonsolidasiController::class, 'konsolidasiDetail'])->name('get-paket-konsolidasi-detail');
Route::get('/paket-konsolidasi-detail-data', [PaketKonsolidasiController::class, 'konsolidasiDetailData'])->name('get-paket-konsolidasi-detail-data');
Route::post('/paket-konsolidasi-detail-update-resiko', [PaketKonsolidasiController::class, 'konsolidasiUpdateResiko'])->name('paket-konsolidasi-update-resiko');
Route::post('/paket-konsolidasi-detail-delete-paket-asli', [PaketKonsolidasiController::class, 'konsolidasiDeletePaket'])->name('paket-konsolidasi-detail-delete-paket-asli');
Route::post('/paket-konsolidasi-detail-delete-paket-all', [PaketKonsolidasiController::class, 'deletePaketAll'])->name('paket-konsolidasi-detail-delete-paket-asli-all');
Route::get('/paket-konsolidasi-detail-report/{anggaran}/{konsolidasi_id}/{allow_download?}/{hide_pareto?}', [ReportController::class, 'konsolidasiDetailData'])->name('get-paket-konsolidasi-detail-report');
Route::post('/paket-konsolidasi-detail-update-nama', [PaketKonsolidasiController::class, 'konsolidasiUpdateName'])->name('paket-konsolidasi-update-nama');
Route::post('/paket-konsolidasi-detail-save-selected', [PaketKonsolidasiController::class, 'saveSelected'])->name('paket-konsolidasi-detail-save-selected');

Route::post('/get-kab-kota', [KementrianController::class, 'getKabKota'])->name('get-kab-kota')->middleware('cors');
Route::get('/get-provinsi/{kl}', [KementrianController::class, 'getProvinsi'])->name('get-provinsi')->middleware('cors');

//Kelompok Paket Konsolidasi
Route::get('/kelompok-paket-konsolidasi', [KelompokKonsolidasi::class, 'index'])->name('get-kelompok-konsolidasi');
Route::post('/kelompok-paket-konsolidasi', [KelompokKonsolidasi::class, 'index'])->name('get-kelompok-konsolidasi-post');
Route::post('/kelompok-paket-konsolidasi/delete', [KelompokKonsolidasi::class, 'delete'])->name('kelompok-konsolidasi-delete');
Route::get('/kelompok-paket-konsolidasi-kecil-tinggi', [KelompokKonsolidasi::class, 'kondisiPertama'])->name('kelompok-konsolidasi-kecil-tinggi');
Route::get('/kelompok-paket-konsolidasi-besar-tinggi', [KelompokKonsolidasi::class, 'kondisiKedua'])->name('kelompok-konsolidasi-besar-tinggi');
Route::get('/kelompok-paket-konsolidasi-kecil-rendah', [KelompokKonsolidasi::class, 'kondisiKetiga'])->name('kelompok-konsolidasi-kecil-rendah');
Route::get('/kelompok-paket-konsolidasi-besar-rendah', [KelompokKonsolidasi::class, 'kondisiKeempat'])->name('kelompok-konsolidasi-besar-rendah');


Route::get('/reload-captcha', [AdminController::class, 'reloadCaptcha']);
//Route::get('/helper/admin/activate', [HelperController::class, 'setAdmin']);
//Route::get('/helper/ignore/clear', [HelperController::class, 'clearIgnoreList']);
Route::get('/helper/log/get', [HelperController::class, 'getLog']);
Route::get('/helper/errorlog/get', [HelperController::class, 'getErrorLog']);
Route::get('/helper/errorlog/clear', [HelperController::class, 'clearErrorLog']);
//Route::get('/helper/banner/rename', [HelperController::class, 'renameBannerFile']);
Route::get('/helper/rup/sync/{year}/{instansiId}', [SirupController::class, 'getRup']);
Route::get('/helper/satker/sync/{year}/{instansiId}', [SirupController::class, 'getSatker']);
Route::get('/helper/instansi/sync', [SirupController::class, 'getInstansi']);
Route::get('/helper/reset/myPassword', [HelperController::class, 'resetMyPassword']);
Route::get('/helper/addadmin/{email}', [HelperController::class, 'addAdmin']);
Route::get('/helper/removeadmin/{email}', [HelperController::class, 'removeAdmin']);

Route::prefix('report')->name('report.')->middleware('cors')->group(function () {
    Route::get('/chart', [ReportController::class, 'index']);
    Route::get('/data', [ReportController::class, 'getData'])->name('data');
    Route::get('/anggaran_pengadaan', [ReportController::class, 'anggaran_pengadaan'])->name('anggaran_pengadaan');
    Route::get('/ringkasan', [ReportController::class, 'ringkasan'])->name('ringkasan');
    Route::get('/ringkasan-data', [ReportController::class, 'getRes'])->name('ringkasan.data');
    Route::post('/datatable', [ReportController::class, 'datatable'])->name('datatable');
    Route::get('/anggaran_terbesar', [ReportController::class, 'anggaranTerbesar'])->name('anggaran_terbesar');
    Route::get('/download', [ReportController::class, 'download'])->name('download');
    Route::get('/pareto', [ReportController::class, 'pareto'])->name('pareto');
    Route::get('/pareto/page/{instansiId}/{tahun}', [ReportController::class, 'paretoPage'])->name('pareto.page');
});

Route::middleware(['auth', 'IsAdminMiddleware'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('dashboard', [AdminController::class, 'index'])->name('dashboard');
    Route::prefix('artikel')->name('artikel.')->group(function () {
        Route::get('/', [ArtikelController::class, 'index'])->name('index');
        Route::get('tambah', [ArtikelController::class, 'create'])->name('tambah');
        Route::post('store', [ArtikelController::class, 'store'])->name('store');

resources/views/web/pages/report/download.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>{{$data->nama_kementrian_lembaga}}</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
	<style type="text/css">
		table tr td,
		table tr th{
			font-size: 9pt;
		}

	</style>

	<div class="row" style="margin-right: 0.5rem;">
		<div class="col-12">
			<div style="margin-bottom: 1rem; text-align: center">
				<h5>Potensi Konsolidasi</h5>
				<h5>{{$data->nama_kementrian_lembaga}} Tahun Anggaran {{$tahun_anggaran}}</h5>
			</div>
			<div class="table-responsive">
				<table id="table_2" class="table table-bordered display" style="width:100%">
					<thead class="table-danger">
						<tr>
							<th rowspan="2">No</th>
							<th rowspan="2"><center>K/L/PD</center></th>
							<th colspan="2"><center>Penyedia</center></th>
							<th colspan="2"><center>Swakelola</center></th>
							<th colspan="2"><center>Penyedia dalam Swakelola</center></th>
							<th colspan="2"><center>Total</center></th>
						</tr>
						<tr>
							<th>Pkt</th>
							<th>Pagu</th>
							<th>Keg</th>
							<th>Pagu</th>
							<th>Pkt</th>
							<th>Pagu</th>
							<th>Keg + Pkt</th>
							<th>Total Pagu</th>
						</tr>
					</thead>
					<tbody>
					<tr>
						<td>1</td>
						<td>{{$data->nama_kementrian_lembaga}}</td>
						<td>{{$paket_penyedia}}</td>
						<td>{{"Rp " . number_format($pagu_pm,0,'','.')}}</td>
						<td>{{$paket_swakelola}}</td>
						<td>{{"Rp " . number_format($pagu_sw,0,'','.')}}</td>
						<td>{{$paket_pds}}</td>
						<td>{{"Rp " . number_format($pagu_pds,0,'','.')}}</td>
						<td>{{$total_paket}}</td>
						<td>{{"Rp " . number_format($total_pagu,0,'','.')}}</td>
					</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>

	<div class="row" style="margin-right: 0.5rem">
		<div class="col-md-12" style="margin-top: 5rem">
			<div style="margin-bottom: 0.5rem;">
				<p>Kategori Berdasarkan Cara Pengadaan</p>
			</div>
			<div class="table-responsive">
				<table class="table table-bordered display" style="width:100%">
					<thead>
						<tr>
							<th>Cara Pengadaan</th>
							<th>Jumlah Pagu</th>
							<th>Jumlah Paket</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($e as $row) 
							<tr>
								<td>{{$row['tipe_paket']}}</td>
								<td>{{"Rp " . number_format($row['pagu'],0,'','.')}}</td>
								<td>{{ $row['paket'] }}</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>

	<div class="row" style="margin-right: 0.5rem">
		<div class="col-md-12" style="margin-top: 5rem">
			<div style="margin-bottom: 0.5rem;">
				<p>Kategori Berdasarkan Jenis Pengadaan</p>
			</div>
			<div class="table-responsive">
				<table class="table table-bordered display" style="width:100%">
					<thead>
						<tr>
							<th>Jenis Pengadaan</th>
							<th>Jumlah Pagu</th>
							<th>Jumlah Paket</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($a as $item) 
							<tr>
								<td>{{$item['jenis_pengadaan']}}</td>
								<td>{{"Rp " . number_format($item['pagu'],0,'','.')}}</td>
								<td>{{ $item['jumlah_paket'] }}</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>

	<div class="row" style="margin-right: 0.5rem">
		<div class="col-md-12" style="margin-top: 5rem">
			<div style="margin-bottom: 0.5rem;">
				<p>Kategori Berdasarkan Metode Pengadaan</p>
			</div>
			<div class="table-responsive">
				<table class="table table-bordered display" style="width:100%">
					<thead>
						<tr>
							<th>Metode Pengadaan</th>
							<th>Jumlah Pagu</th>
							<th>Jumlah Paket</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($mp as $item) 
							<tr>
								<td>{{$item['metode_pengadaan']}}</td>
								<td>{{"Rp " . number_format($item['pagu'],0,'','.')}}</td>
								<td>{{ $item['jumlah_paket'] }}</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>

	<script>

		const ctx1 = document.getElementById('myChart1');
		const myChart1 = new Chart(ctx1, {
        type: 'doughnut',
        data: {
            labels: [
                @foreach($e as $b)
                '{{ $b["tipe_paket"] }}',
                @endforeach
            ],
            datasets: [{
                label: '# of Votes',
                data: [
                    @foreach($e as $b)
                    '{{ $b["pagu"] }}',
                    @endforeach
                ],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(175, 192, 192, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(175, 192, 192, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });
	</script>
</body>
</html>

resources/views/web/pages/report/report-konsolidasi-list.blade.php
@extends('web.layouts.global')
@section('content')
@php
    $no=1
@endphp
<div class="row justify-content-md-center mt-4">
    @if($allowDownload)
        <div class="col-md-auto">
            <a href="javascript:void(0)" id="downloadExcel" class="btn btn-primary">Unduh Rangkuman Hasil</a>
        </div>
    @endif

    @if(!$hidePareto)
        <div class="col-md-auto">
            <a href="{{ route('report.pareto.page', ['instansiId' => $instansiId, 'tahun' => $tahun])}}" target = "_blank"class="btn btn-success">Lihat Pareto</a>
        </div>
    @endif
</div>
<div class="row mb-4" id="report" tag="report">
    <div class="col-12">
        <div class="row mt-10">
            <div class="col-12">
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <p style="font-size: 14pt; font-weight: bold; text-align: center">{{ ucwords($namaPaket)}} <br>
                        </p>
                        <div class="table-responsive" style="margin-top: 2rem">
                            <table class="table table-bordered display" style="width:100%" id="tabledata" name="tabledata">
                                <thead class="table-danger">
                                    <tr>
                                        <th >No</th>
                                        <th >ID Sirup</th>
                                        <th >Nama Paket</th>
                                        <th >Satker</th>
                                        <th >Klasifikasi Anggaran</th>
                                        <th >Metode</th>
                                        <th >Jenis</th>
                                        <th >PPK</th>
                                        <th >Pagu Anggaran</th>
                                    </tr>
                                </thead>
                                <tbody id="t_body">
                                    <?php
                                        $total = 0;
                                    ?>
                                    @foreach ($data as $item)
                                        
                                    <?php
                                        $total = $total + $item['pagu_anggaran']
                                    ?>
                                    <tr>
                                        <td>{{$no++}}</td>
                                        <td>{{$item['id_sirup']}}</td>
                                        <td>{{$item['nama_paket_asli']}}</td>
                                        <td>{{$item['nama_satker']}}</td>
                                        <td>{{$item['klasifikasi_anggaran']  }}</td>
                                        <td>{{$item['metode_pengadaan'] }}</td>
                                        <td>{{$item['jenis_pengadaan'] }}</td>
                                        <td>{{$item['ppk']}}</td>
                                        <td style="text-align: right">{{!$allowDownload ? number_format($item['pagu_anggaran'], 0, '', '.') :$item['pagu_anggaran']}}</td>
                                    </tr>
                                    @endforeach
                                    <tr>
                                        <td colspan="8"> Total </td>
                                        <td style="text-align: right"> {{ !$allowDownload ? number_format($total, 0, '', '.') : $total}}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                
    
            </div>
        </div>
    </div>
</div>

@endsection

@push('script')
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js" integrity="sha512-GsLlZN/3F2ErC5ifS5QtgpiJtWd43JWSuIgh7mbzZ8zBps+dvLusV+eNQATqgA/HdeKFVgA5v3S/cIrLF7QnIg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js"></script>
    <script>
         $(document).ready(function(){
            let str = "{{ ucwords($paket->nama_paket_konsolidasi)}}";

            $('#downloadPdf').click(function(event) {
       
//                 var element = document.getElementById('report');
// html2pdf(element);

            var divContents = $("#report").html();
            var printWindow = window.open('', '', 'height=400,width=800');
            // printWindow.document.write('<html><head><title>DIV Contents</title>');
            // printWindow.document.write('</head><body >');
            printWindow.document.write(divContents);
            // printWindow.document.write('</body></html>');
            printWindow.document.close();
            printWindow.print();
                // New Promise-based usage:
                //html2pdf().set(opt).from(element).save();

                //window.jsPDF = window.jspdf.jsPDF;
                //window.html2canvas = html2canvas

                // html2canvas(document.querySelector('#report')).
                //     then(canvas => {
                //         const img = canvas.toDataURL('image/png')

                //         var pdf = new jsPDF("p","mm","Legal");
                //         pdf.addImage(img, 'PNG', 6,2,204,356)
                //         pdf.save(str + '.pdf');
                //     })
                // // get size of report page
                // var reportPageHeight = $('#reportPage').innerHeight();
                // var reportPageWidth = $('#reportPage').innerWidth();
            
            });

            function exportReportToExcel() {
                
            }

            $('#downloadExcel').click(function(event) {
                HtmlTOExcel('xlsx')
            });

            function HtmlTOExcel(type, fun, dl) {
                var elt = document.getElementById('tabledata');
                var wb = XLSX.utils.table_to_book(elt, { sheet: "sheet1" });
                return dl ?
                    XLSX.write(wb, { bookType: type, bookSST: true, type: 'base64' }) :
                    XLSX.writeFile(wb, fun || ('{{ $paket->nama_paket_konsolidasi }}' + '.' + (type || 'xlsx')));
            }


        });

        
      
    </script>
@endpush

resources/views/web/pages/report/ringkasan2.blade.php
@extends('web.layouts.global')
@section('content')
@php
    $no=1
@endphp
<div class="row mb-4" id="report">
    <div class="col-12">
        <div class="row mt-10">
            <div class="col-12">
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <p style="font-size: 14pt; font-weight: bold; text-align: center">Potensi Konsolidasi <br>
                            @foreach ($res as $item)   
                                {{$item['klpd']}}
                            @endforeach
                            Tahun Anggaran {{$uip->tahun}}</p>
                        <div class="table-responsive" style="margin-top: 2rem">
                            <table class="table table-bordered display" style="width:100%">
                                <thead class="table-danger">
                                    <tr>
                                        <th rowspan="2">No</th>
                                        <th rowspan="2"><center>K/L/PD</center></th>
                                        <th colspan="2"><center>Penyedia</center></th>
                                        <th colspan="2"><center>Swakelola</center></th>
                                        <th colspan="2"><center>Penyedia dalam Swakelola</center></th>
                                        <th colspan="2"><center>Total</center></th>
                                    </tr>
                                    <tr>
                                        <th>Pkt</th>
                                        <th>Pagu</th>
                                        <th>Keg</th>
                                        <th>Pagu</th>
                                        <th>Pkt</th>
                                        <th>Pagu</th>
                                        <th>Keg + Pkt</th>
                                        <th>Total Pagu</th>
                                    </tr>
                                </thead>
                                <tbody id="t_body">
                                    @foreach ($res as $item)
                                        <tr>
                                            <td>{{$no++}}</td>
                                            <td>{{$item['klpd']}}</td>
                                            <td>{{ number_format($item['paket']) }}</td>
                                            <td>{{ "Rp ". number_format($item['pagu'],0,'','.') }}</td>
                                            <td>{{ number_format($item['paket']) }}</td>
                                            <td>{{ "Rp ". number_format($item['pagu'],0,'','.') }}</td>
                                            <td>{{ number_format($item['paket']) }}</td>
                                            <td>{{ "Rp ". number_format($item['pagu'],0,'','.') }}</td>
                                            <td>
                                                {{ $item['paket'] + $item['paket'] + $item['paket'] }}
                                            </td>
                                            <td>
                                                @php
                                                    $tp = $item['pm']['pagu'] + $item['sw']['pagu'] + $item['pds']['pagu'];
                                                @endphp
                                                {{ "Rp ". number_format($tp,0,'','.') }}
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
    
            </div>
        </div>
        
        <div class="row" style="margin-top: 3rem;" id="chart">
            <div class="col-12">
                <div class="row">
                    <p style="font-size: 16pt; font-weight: bolder; margin-bottom: 2rem; text-decoration: underline;">Kategori Berdasarkan Cara Pengadaan</p>
                    <div class="col-5">
                        <canvas id="myChart1" height="200"></canvas>
                    </div>
                    <div class="col-7">
                        <div class="table-responsive">
                            <table id="table_cara" class="table table-bordered" style="width: 100%">
                                <thead>
                                    <th>Cara Pengadaan</th>
                                    <th>Pagu</th>
                                    <th class="text-right">Jumlah Paket</th>
                                </thead>
                                <tbody>
                                    {{-- <tr>
                                        <td>{{$item['pm']['tipe']}}</td>
                                        <td>{{"Rp " . number_format($item['pm']['pagu'],0,'','.')}}</td>
                                        <td class="text-right">{{ number_format($item['pm']['paket']) }}</td>
                                    </tr>
                                    <tr>
                                        <td>{{$item['sw']['tipe']}}</td>
                                        <td>{{"Rp " . number_format($item['sw']['pagu'],0,'','.')}}</td>
                                        <td class="text-right">{{ number_format($item['sw']['paket']) }}</td>
                                    </tr>
                                    <tr>
                                        <td>{{$item['pds']['tipe']}}</td>
                                        <td>{{"Rp " . number_format($item['pds']['pagu'],0,'','.')}}</td>
                                        <td class="text-right">{{ number_format($item['pds']['paket']) }}</td>
                                    </tr> --}}
                                </tbody>
                                <tfoot>
                                    {{-- <tr>
                                        <td class="font-weight: bolder;">Total</td>
                                        <td>{{"Rp ". number_format($e['total']['total_pagu'],0,'','.') }}</td>
                                        <td class="text-right">{{ number_format($e['total']['jumlah_paket']) }}</td>
                                    </tr> --}}
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        
            <div class="row" style="margin-top: 4rem">
                <div class="col-12">
                    <div class="table-responsive">
                        <table class="table table-stripped table-bordered">
                            <tbody>
                                {{-- @foreach ($paketKonsolidasi as $item) 
                                    <tr>
                                        <td>{{$item->nama_paket_konsolidasi}}</td>
                                    </tr>
                                @endforeach --}}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row justify-content-md-center mt-4">
    <div class="col-md-auto">
        <a href="javascript:void(0)" id="downloadPdf" class="btn btn-primary" data-html2canvas-ignore>Unduh Rangkuman Hasil</a>
        {{-- <a href="{{ route('report.generate') }}" class="btn btn-primary">Unduh Rangkuman Hasil</a> --}}
    </div>
</div>

@endsection

@push('script')
    <script>
        $(document).ready(function(){

            let data = []
            $.ajax({
                url: "{{ route('report.ringkasan.data') }}",
                success: function(d){
                    data.push(d)
                    console.log(data)
                }
            })


            const ctx1 = document.getElementById('myChart1'); 
            const myChart = new Chart(ctx1, {
                type: 'pie',
                data: {
                    labels: ['Penyedia','Swakelola','Penyedia dalam Swakelola'],
                    datasets: [{
                        label: '# of Votes',
                        data: [
                            
                        ],
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(175, 192, 192, 0.2)',
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(175, 192, 192, 1)'
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                }
            });
        });


    </script>
@endpush